package com.example.controller;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ResponseBody;

import com.example.demo.accessingdatamysql.MAKER_MASTER;
import com.example.demo.accessingdatamysql.MAKER_MASTERRepository;

@Controller
public class Main {
	final static Logger logger = LoggerFactory.getLogger(Main.class);

	// This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	@Autowired
	private MAKER_MASTERRepository makerMasterRepository;

	public @ResponseBody Iterable<MAKER_MASTER> getAllMakerMaster() {
		//		return makerMasterRepository.findAllByTorokusha("'hashimotomasaru'");
		return makerMasterRepository.findAll();
	}
}